name: checkmark
description: Animated check mark. Customise colors, curves, duration, and more.
version: 0.0.1
homepage: https://github.com/sourcemain/checkmark
repository: https://github.com/sourcemain/checkmark

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0